minecraftServers:
  hostname: "mc-servers.com"
  portAllocation:
    strategy: "pre-allocated"
    ports:
      - 25566
      - 25567
      - 25568
      - 25569

admin:
  username: "steve"
  # tartare2boeuf
  hashedPassword: "$2y$10$ijt.SMna.a/0n803t8/6FOTSDdBdeo/jRqALM/Xm/uWxxSi5fwA7O"
