# https://taskfile.dev

version: '3'

tasks:
  default:
    silent: true
    cmds:
      - task --list-all

  templ:
    internal: true
    cmds:
      - templ generate

  tailwind:
    internal: true
    cmds:
      - npx @tailwindcss/cli -i ./internal/apps/web/ui/assets/css/input.css -o ./internal/apps/web/ui/assets/css/styles.css

  build:
    deps: [templ, tailwind]
    aliases: [b]
    cmds:
      - go build -v -o ./bin/server ./cmd/server/main.go

  clean:
    cmds:
      - rm -rf ./bin
      - go clean

  test:
    aliases: [t]
    cmds:
      - go test ./...

  lint:
    cmds:
      - golangci-lint run

  run:
    cmds:
      - air
